[package]
name = "wasm-utils"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
parity-wasm = { git="https://github.com/nikvolf/parity-wasm" }
log = "0.3"
env_logger = "0.4"
lazy_static = "0.2"

[lib]

[[bin]]
name = "wasm-opt"
path = "opt/src/main.rs"

[[bin]]
name = "wasm-ext"
path = "ext/src/main.rs"

[[bin]]
name = "wasm-gas"
path = "gas/src/main.rs"